### ISSUE TITLE
文章推荐 - ECMAScript Modules in Browsers

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#1]
>**类别：**[JS](/discountry/wait-for-translate/tree/master/JS/)
>**原文链接：**[ECMAScript Modules in Browsers](https://jakearchibald.com/2017/es-modules-in-browsers/)
>**作者：**[Jake Archibald](https://twitter.com/jaffathecake)

**Comment by yeszhangyi** [comment]
一波带走

**Comment by discountry** [comment]
@yeszhangyi 好的

**Comment by discountry** [comment]
翻译质量较差，像机器翻译，对一些术语使用不准确，希望下次能够再接再厉，文章已校对完毕，请再次检查后发表至知乎。

**Comment by yeszhangyi** [comment]
好的。我也是特意挑了篇短的，结果是转载的，点开外联发现多了好多，自己确实没有理解，下次领自己比较熟悉的。
