### ISSUE TITLE
文章推荐 - The Many Faces of Functions in JavaScript

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#10]
>**类别：**[JS](/discountry/wait-for-translate/tree/master/JS)
>**原文链接：**[The Many Faces of Functions in JavaScript](https://bocoup.com/blog/the-many-faces-of-functions-in-javascript)
>**作者：**[Leo Balter](https://bocoup.com/about/bocouper/leo-balter) & [Rick Waldron](https://bocoup.com/about/bocouper/rick-waldron)

**Comment by ghost** [comment]
I want to choose this one.

**Comment by discountry** [comment]
@Liubara 好的

**Comment by ghost** [comment]
提交了函数定义的多种方法第一版。

**Comment by discountry** [comment]
@Liubara 你自己再检查一下就可以发表啦~

**Comment by ghost** [comment]
好的谢谢~

**Comment by ghost** [comment]
改了些细节...

**Comment by discountry** [comment]
请重新编辑提交袄，我帮你校对的部分你没有pull下来，现在冲突了无法合并。

**Comment by ghost** [comment]
好的

**Comment by ghost** [comment]
这次好像没有冲突了...可以直接关掉这个Issue了...
