### ISSUE TITLE
文章推荐 - JavaScript — A First-Class Language At Last

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#11]
>**类别：**[JS](/discountry/wait-for-translate/tree/master/JS)
>**原文链接：**[JavaScript — A First-Class Language At Last](https://hackernoon.com/javascript-a-first-class-language-at-last-209376f69731)
>**作者：**[Tom GoldenbergFollow](https://hackernoon.com/@tomgoldenberg)

**Comment by leviding** [comment]
翻译认领 @discountry

**Comment by discountry** [comment]
@leviding 好的

**Comment by leviding** [comment]
翻译完成，已 PR 。

**Comment by discountry** [comment]
@leviding 并未收到PR

**Comment by leviding** [comment]
@discountry 我检查了下，确实没 PR 成功。我又弄了下，现在好了。

**Comment by discountry** [comment]
@leviding 检查一下差不多可以发表啦~

文章现在没有翻译过来的标题吗？

**Comment by leviding** [comment]
有标题
《JavaScript，一流的编程语言》
这个怎么样
