### ISSUE TITLE
文章推荐 - 50 Best Resources When Learning to Code

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#13]
>**类别：**[Stories](/discountry/wait-for-translate/tree/master/Stories)
>**原文链接：**[50 Best Resources When Learning to Code](https://themission.co/50-best-resources-when-learning-to-code-496cefc29507)
>**作者：**[Pavel Malos](https://themission.co/@pavel.malos)

**Comment by shadow-mike** [comment]
你好，我想尝试翻译这篇文章。

**Comment by discountry** [comment]
@shadow512122313 好的

**Comment by shadow-mike** [comment]
[翻译初稿完成](https://github.com/discountry/wait-for-translate/pull/28)

**Comment by discountry** [comment]
@shadow512122313 再检查一下就可以发表啦
