### ISSUE TITLE
文章推荐 - We asked 20,000 people who they are and how they’re learning to code

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#15]
>**类别：**[Stories](/discountry/wait-for-translate/tree/master/Stories)
>**原文链接：**[We asked 20,000 people who they are and how they’re learning to code](https://medium.freecodecamp.com/we-asked-20-000-people-who-they-are-and-how-theyre-learning-to-code-fff5d668969)
>**作者：**[Quincy Larson](https://medium.freecodecamp.com/@quincylarson)

**Comment by yeszhangyi** [comment]
你好，我想翻译这篇。

**Comment by discountry** [comment]
@yeszhangyi 好的，注意翻译质量。

**Comment by discountry** [comment]
@yeszhangyi 再检查一下就可以发表啦
