### ISSUE TITLE
文章推荐 - Understanding Node.js Event-Driven Architecture

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#16]
>**类别：**[JS](/discountry/wait-for-translate/tree/master/JS)
>**原文链接：**[Understanding Node.js Event-Driven Architecture](https://medium.freecodecamp.com/understanding-node-js-event-driven-architecture-223292fcbc2d)
>**作者：**[Samer Buna](https://medium.freecodecamp.com/@samerbuna)

**Comment by Jupiter-Lee** [comment]
我来翻译这篇

**Comment by discountry** [comment]
@Jupiter-Lee 好的

**Comment by discountry** [comment]
@Jupiter-Lee 注意格式，可以参考已发表的文章。另外译文只需要保留中文部分即可，再检查修订一下就可以发表啦~
