### ISSUE TITLE
文章推荐 - Quantum Up Close: What is a browser engine?

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#20]
>**类别：**[Stories](/discountry/wait-for-translate/tree/master/Stories)
>**原文链接：**[Quantum Up Close: What is a browser engine?](https://hacks.mozilla.org/2017/05/quantum-up-close-what-is-a-browser-engine/)
>**作者：**[Potch](http://potch.me/)

**Comment by codeArvin** [comment]
i want to translate it

**Comment by wufenfen** [comment]
I saw someone from Juejin's translation team have done that. So, what do u think that one blog will or has been translated by several people?

**Comment by discountry** [comment]
If you're expecting to translate the article well & precisely. You'd have to read the whole article over and over.

In that case, collaboration won't save you time, besides, translators have their own language flavour. It's weird to just mix them up.

**Comment by wufenfen** [comment]
I will do it.
