### ISSUE TITLE
文章推荐 - Create an Animated Sticky Navigation Menu with Vanilla JavaScript

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#3]
>**类别：**[JS](/discountry/wait-for-translate/tree/master/JS)
>**原文链接：**[Create an Animated Sticky Navigation Menu with Vanilla JavaScript](https://www.sitepoint.com/animated-sticky-navigation-menu-javascript/)
>**作者：**[Albert Senghor](https://www.sitepoint.com/author/asenghor/)

**Comment by codeArvin** [comment]
I want to translate it

**Comment by discountry** [comment]
@codeArvin 好哒

**Comment by discountry** [comment]
#5 请等待分支合并收录译文。

**Comment by discountry** [comment]
@codeArvin 请将校对后的文本发表至知乎专栏，可以对文字稍作润色，更加口语化一些。

**Comment by codeArvin** [comment]
好哒
