### ISSUE TITLE
文章推荐 - Creating Media Queries for Responsive Web Designs

### ISSUE THREAD

**Issue by discountry** [discountry/wait-for-translate#4]
>**类别：**[CSS](/discountry/wait-for-translate/tree/master/CSS)
>**原文链接：**[Creating Media Queries for Responsive Web Designs](https://www.sitepoint.com/creating-media-queries-for-responsive-web-designs/)
>**作者：**[Chris Ward](https://www.sitepoint.com/author/cward/)

**Comment by ghost** [comment]
I want to translate this article.

**Comment by Liubara** [comment]
oh no, article

**Comment by discountry** [comment]
@Liubara 好的袄。

**Comment by ghost** [comment]
I have pulled the translated one.

**Comment by discountry** [comment]
请处理文中句子生硬不自然部分。

**Comment by ghost** [comment]
更改了一些表述...余大可以看看...

**Comment by discountry** [comment]
刚刚合并了一下，你再检查一遍

**Comment by ghost** [comment]
好的

**Comment by ghost** [comment]
改了关于and和or逻辑那里的阐述...

**Comment by discountry** [comment]
@Liubara 准备发布到知乎吧

**Comment by ghost** [comment]
好的。

**Comment by ghost** [comment]
文章已发表。谢谢余大提供的机会~
